# Generated by Django 5.2.3 on 2025-06-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducacionInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_inicial/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_inicial', to='panel_datos.ciclosescolares')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionMediaSuperior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_media_superior/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_med_sup', to='panel_datos.ciclosescolares')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionPreescolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_preescolar/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_preescolar', to='panel_datos.ciclosescolares')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionPrimaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_primaria/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_primaria', to='panel_datos.ciclosescolares')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionSecundaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_secundaria/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_secundaria', to='panel_datos.ciclosescolares')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionSuperior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='txt_superior/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_edu_superior', to='panel_datos.ciclosescolares')),
            ],
        ),
    ]
