# Generated by Django 5.2.3 on 2025-06-23 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0002_educacioninicial_educacionmediasuperior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginacionLocalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='marginacion_por_localidad/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProyeccionesPoblacionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('archivo', models.FileField(upload_to='csv_pob_mitad/')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
