# Generated by Django 5.2.3 on 2025-06-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0003_marginacionlocalidad_proyeccionespoblacionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturEscolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('PE', 'Preescolar'), ('PR', 'Primaria'), ('SE', 'Secundaria'), ('MS', 'Media Superior'), ('SU', 'Superior'), ('TO', 'Total')], max_length=2)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('valor', models.IntegerField()),
                ('interpretacion', models.TextField(max_length=1000)),
                ('formula_de_calculo', models.FileField(upload_to='formulas_cobertura_escolar/')),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_cobertura_escolar', to='panel_datos.ciclosescolares')),
            ],
        ),
    ]
