# Generated by Django 5.2.3 on 2025-06-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0004_coberturescolar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoberturEscolar',
            new_name='CoberturaEscolar',
        ),
    ]
