# Generated by Django 5.2.3 on 2025-07-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0005_rename_coberturescolar_coberturaescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionPoblacion345',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_antecion_hombres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_atencion_mujeres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_atencion_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proyeccion_conapo_poblacion_hombres', models.IntegerField()),
                ('proyeccion_conapo_poblacion_mujeres', models.IntegerField()),
                ('proyeccion_conapo_poblacion_total', models.IntegerField()),
                ('grupo_de_edad', models.CharField(choices=[('3', '3 años'), ('4', '4 años'), ('5', '5 años'), ('3-5', '3, 4 y 5 años')], max_length=3)),
                ('grafico', models.FileField(upload_to='atencion_poblacion_edades_3_4_5/')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_atencion_poblacion_345', to='panel_datos.ciclosescolares')),
            ],
        ),
    ]
