# Generated by Django 5.2.3 on 2025-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0006_atencionpoblacion345'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionpoblacion345',
            name='matricula_hombres',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atencionpoblacion345',
            name='matricula_mujeres',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atencionpoblacion345',
            name='matricula_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencionpoblacion345',
            name='grafico',
            field=models.ImageField(upload_to='atencion_poblacion_edades_3_4_5/'),
        ),
        migrations.AddConstraint(
            model_name='atencionpoblacion345',
            constraint=models.UniqueConstraint(fields=('ciclo_escolar_inicio', 'grupo_de_edad'), name='unique_atencion_por_ciclo_y_edad'),
        ),
    ]
