# Generated by Django 5.2.3 on 2025-07-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0007_atencionpoblacion345_matricula_hombres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencionpoblacion345',
            old_name='porcentaje_antecion_hombres',
            new_name='porcentaje_atencion_hombres',
        ),
    ]
