# Generated by Django 5.2.3 on 2025-07-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0008_rename_porcentaje_antecion_hombres_atencionpoblacion345_porcentaje_atencion_hombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='graficos_multiples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(choices=[('AE3', 'Atención Edad 3 años'), ('AE4', 'Atención Edad 4 años'), ('AE5', 'Atención Edad 5 años')], max_length=3)),
                ('grafico', models.ImageField(upload_to='graficos_multiplesciclos/')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('primer_ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_ciclo_grafico_multiple', to='panel_datos.ciclosescolares')),
                ('ultimo_ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_ciclo_grafico_multiple', to='panel_datos.ciclosescolares')),
            ],
        ),
    ]
