# Generated by Django 5.2.3 on 2025-10-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0010_indicadordefinicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadordefinicion',
            name='indicador',
            field=models.CharField(choices=[('AE3', 'Atención Edad 3 años'), ('AE4', 'Atención Edad 4 años'), ('AE5', 'Atención Edad 5 años')], max_length=3),
        ),
    ]
