# Generated by Django 5.2.3 on 2025-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0011_alter_indicadordefinicion_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='interpretaciones_indicadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(choices=[('AE3', 'Atención Edad 3 años'), ('AE4', 'Atención Edad 4 años'), ('AE5', 'Atención Edad 5 años')], max_length=3)),
                ('definicion', models.TextField(max_length=1000)),
            ],
        ),
    ]
