# Generated by Django 5.2.3 on 2025-10-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0012_interpretaciones_indicadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpretaciones_indicadores',
            old_name='definicion',
            new_name='interpretacion',
        ),
    ]
