# Generated by Django 5.2.3 on 2025-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0013_rename_definicion_interpretaciones_indicadores_interpretacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='algoritmos_indicadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(choices=[('AE3', 'Atención Edad 3 años'), ('AE4', 'Atención Edad 4 años'), ('AE5', 'Atención Edad 5 años')], max_length=3)),
                ('algoritmo', models.ImageField(upload_to='algoritmos_indicadores/')),
            ],
        ),
    ]
