# Generated by Django 5.2.3 on 2025-11-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0014_algoritmos_indicadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginacionlocalidad',
            name='actualizado_por',
        ),
        migrations.AddField(
            model_name='marginacionlocalidad',
            name='ciclo_escolar_inicio',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='inicio_marginacion_poblacion345', to='panel_datos.ciclosescolares'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MarginacionPoblacion345',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_muy_bajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_bajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_medio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_muy_alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matricula_total', models.IntegerField()),
                ('proyeccion_conapo_poblacion_total', models.IntegerField()),
                ('grupo_de_edad', models.CharField(choices=[('3', '3 años'), ('4', '4 años'), ('5', '5 años'), ('3-5', '3, 4 y 5 años')], max_length=3)),
                ('grafico', models.ImageField(upload_to='marginacion_poblacion_edades_3_4_5/')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualizacion')),
                ('ciclo_escolar_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_marginacion_poblacion_345', to='panel_datos.ciclosescolares')),
            ],
        ),
    ]
