# Generated by Django 5.2.3 on 2025-11-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0016_marginacionlocalidad_actualizado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginacionlocalidad',
            name='ciclo_escolar_inicio',
        ),
    ]
