# Generated by Django 5.2.3 on 2026-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0017_remove_marginacionlocalidad_ciclo_escolar_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginacionpoblacion345',
            name='indicador',
            field=models.CharField(choices=[('AE3', 'Atención Edad 3 años'), ('AE4', 'Atención Edad 4 años'), ('AE5', 'Atención Edad 5 años')], default='AE3', max_length=3),
            preserve_default=False,
        ),
    ]
