# Generated by Django 5.2.3 on 2026-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_datos', '0018_marginacionpoblacion345_indicador'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='graficos_multiples',
            constraint=models.UniqueConstraint(fields=('primer_ciclo_escolar', 'ultimo_ciclo_escolar', 'indicador'), name='unique_graficos_multiples_por_ciclo_e_indicador'),
        ),
        migrations.AddConstraint(
            model_name='marginacionpoblacion345',
            constraint=models.UniqueConstraint(fields=('ciclo_escolar_inicio', 'grupo_de_edad'), name='unique_marginacion_por_ciclo_y_edad'),
        ),
    ]
